{% set version = "7.1.0r" %}
{% set ver = version.replace(".", "_") %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: http://www.earthsystemmodeling.org/esmf_releases/public/ESMF_{{ ver }}/esmf_{{ ver }}_src.tar.gz
  sha256: ae9a5edb8d40ae97a35cbd4bd00b77061f995c77c43d36334dbb95c18b00a889


build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - python
    - numpy
    - esmf {{ version }}
  run:
    - python
    - numpy
    - esmf {{ version }}

test:
  imports:
    - ESMF

about:
  home: https://www.earthsystemcog.org/projects/esmpy/
  license: The University of Illinois/NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - rokuingh
