travis:
  secure:
    BINSTAR_TOKEN: b0q31Dcpec7nFJhkKAoWlOII6R+EVLpL0W+lZW+5mcgwITt7QUvcOZndMBczYJFMOg3yMyZCLFBvzP81kF5nDkeKUxsgzOkWkP4n3ptNyKfbxgeuvy+PgVD4Fx+zgJlps7/3GsRHs9OspNfoNw794pVPYfKM4jNNAYl0sbBVxbjMImgyAfBX1J7kj1HwBeEtwMcgt9vxCjKN+Q6m/XBWck7HHHHBLWz8wJi/iUB9YIxj9o7EpoHJ2ob8qxTbNFk+ZZ9Utiz0vMDvf0/2F1G9kCdki1oYVcMVWRLCs9+fxcV2pRzA/N177/Z259nzLA5US5q+utrDeW1ZawUN9sMLh0W9tpTjH0vz8oq3ztPMReTJT6YM0i2MRMPkrJvhhxnbyBNwt7H5X78TlC93NXJwPL/rp2WvpCG7o2x4g1iGWp+X5RvGKexDpIvf2t8xFju2ItTlRt7M/pgzBI9f0zxIHEv4agDujCdCVBQ5IPSa9iXmhunD5TPpwHizE7dqd9+H0haekxODTusxLj1YG6sYi+Weq19cxNnTHE1WizIjEnJodLB14idMf/W7nV4/hEMjDBlgL9HnsglD+CSocIzchlcZFKCw3ms63pf+yiHDhWkVnyO2D1SYDjBCFdVw4o8W1R7/uro63oYLp5Y/4CVoqaHQ50uDjQRC3dDV4IP5nRQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
